# -*- coding: utf-8 -*-
"""
Created on Tue Jul  7 14:09:03 2015

@author: Pierre Jacquot
@modify: Eric Rohmer
"""

import sim

#Get the handles of all NAO in the scene
def get_all_handles(nbrOfNao,clientID,Body):
    print '-> Head for NAO : '+ str(1)
    Body[0].append(sim.simxGetObjectHandle(clientID,'HeadYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[1].append(sim.simxGetObjectHandle(clientID,'HeadPitch#',sim.simx_opmode_oneshot_wait)[1])
    #Bottom
    print '-> Bottom for NAO : ' + str(1)
    Body[2].append(sim.simxGetObjectHandle(clientID,'HipRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[3].append(sim.simxGetObjectHandle(clientID,'HipPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[4].append(sim.simxGetObjectHandle(clientID,'KneePitch#',sim.simx_opmode_oneshot_wait)[1])
    #Wheels
    #print '-> Wheels for NAO : ' + str(1)
    #Body[5].append(sim.simxGetObjectHandle(clientID,'WheelFL#',sim.simx_opmode_oneshot_wait)[1])
    #Body[6].append(sim.simxGetObjectHandle(clientID,'WheelB#',sim.simx_opmode_oneshot_wait)[1])
    #Body[7].append(sim.simxGetObjectHandle(clientID,'WheelFR#',sim.simx_opmode_oneshot_wait)[1])
    #Left Arm
    print '-> Left Arm for NAO : ' + str(1)
    Body[5].append(sim.simxGetObjectHandle(clientID,'LShoulderPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[6].append(sim.simxGetObjectHandle(clientID,'LShoulderRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[7].append(sim.simxGetObjectHandle(clientID,'LElbowYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[8].append(sim.simxGetObjectHandle(clientID,'LElbowRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[9].append(sim.simxGetObjectHandle(clientID,'LWristYaw#',sim.simx_opmode_oneshot_wait)[1])
    #Right Arm
    print '-> Right Arm for NAO : ' + str(1)
    Body[10].append(sim.simxGetObjectHandle(clientID,'RShoulderPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[11].append(sim.simxGetObjectHandle(clientID,'RShoulderRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[12].append(sim.simxGetObjectHandle(clientID,'RElbowYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[13].append(sim.simxGetObjectHandle(clientID,'RElbowRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[14].append(sim.simxGetObjectHandle(clientID,'RWristYaw#',sim.simx_opmode_oneshot_wait)[1])
    #Left fingers
    print '-> Left Fingers for NAO : ' + str(1)
    Body[15].append(sim.simxGetObjectHandle(clientID,'LHand#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger21#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger22#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger23#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger11#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger12#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger13#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger41#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger42#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger43#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger31#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger32#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger33#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb1#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb2#',sim.simx_opmode_oneshot_wait)[1])
    Body[16].append(Body[15][0:15])
    #Right Fingers
    print '-> Right Fingers for NAO : ' + str(1)
    Body[17].append(sim.simxGetObjectHandle(clientID,'RHand#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger41#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger42#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger43#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger31#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger32#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger33#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger21#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger22#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger23#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger11#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger12#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger13#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb1#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb2#',sim.simx_opmode_oneshot_wait)[1])
    Body[18].append(Body[17][0:15]) 
    for i in range(0, nbrOfNao-1):
        print '-> Head for NAO : '+ str(i+2)
        Body[0].append(sim.simxGetObjectHandle(clientID,'HeadYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[1].append(sim.simxGetObjectHandle(clientID,'HeadPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Bottom
        print '-> Bottom for NAO : ' + str(i+2)
        Body[2].append(sim.simxGetObjectHandle(clientID,'HipRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[3].append(sim.simxGetObjectHandle(clientID,'HipPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[4].append(sim.simxGetObjectHandle(clientID,'KneePitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Wheels
        #print '-> Wheels for NAO : ' + str(i+2)
        #Body[5].append(sim.simxGetObjectHandle(clientID,'WheelFL#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Body[6].append(sim.simxGetObjectHandle(clientID,'WheelB#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Body[7].append(sim.simxGetObjectHandle(clientID,'WheelFR#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Left Arm
        print '-> Left Arm for NAO : ' + str(i+2)
        Body[5].append(sim.simxGetObjectHandle(clientID,'LShoulderPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[6].append(sim.simxGetObjectHandle(clientID,'LShoulderRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[7].append(sim.simxGetObjectHandle(clientID,'LElbowYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[8].append(sim.simxGetObjectHandle(clientID,'LElbowRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[9].append(sim.simxGetObjectHandle(clientID,'LWristYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Right Arm
        print '-> Right Arm for NAO : ' + str(i+2)
        Body[10].append(sim.simxGetObjectHandle(clientID,'RShoulderPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[11].append(sim.simxGetObjectHandle(clientID,'RShoulderRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[12].append(sim.simxGetObjectHandle(clientID,'RElbowYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[13].append(sim.simxGetObjectHandle(clientID,'RElbowRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[14].append(sim.simxGetObjectHandle(clientID,'RWristYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Left fingers
        print '-> Left Fingers for NAO : ' + str(i+2)
        Body[15].append(sim.simxGetObjectHandle(clientID,'LHand#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger21#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger22#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger23#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger11#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger12#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger13#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger41#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger42#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger43#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger31#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger32#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger33#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb1#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb2#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[16].append(Body[15][i*15:(i+1)*15])
        #Right Fingers
        print '-> Right Fingers for NAO : ' + str(i+2)
        Body[17].append(sim.simxGetObjectHandle(clientID,'RHand#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger41#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger42#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger43#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger31#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger32#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger33#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger21#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger22#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger23#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger11#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger12#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger13#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb1#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb2#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[18].append(Body[17][i*15:(i+1)*15])

#Get the Handles of all NAOs except the first one
def get_new_nao_handles(nbrOfNao,clientID,Body):
    for i in range(0, nbrOfNao-1):
        print '-> Head for NAO : '+ str(i+2)
        Body[0].append(sim.simxGetObjectHandle(clientID,'HeadYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[1].append(sim.simxGetObjectHandle(clientID,'HeadPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Bottom
        print '-> Bottom for NAO : ' + str(i+2)
        Body[2].append(sim.simxGetObjectHandle(clientID,'HipRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[3].append(sim.simxGetObjectHandle(clientID,'HipPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[4].append(sim.simxGetObjectHandle(clientID,'KneePitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Wheels
        #print '-> Wheels for NAO : ' + str(i+2)
        #Body[5].append(sim.simxGetObjectHandle(clientID,'WheelFL#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Body[6].append(sim.simxGetObjectHandle(clientID,'WheelB#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Body[7].append(sim.simxGetObjectHandle(clientID,'WheelFR#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Left Arm
        print '-> Left Arm for NAO : ' + str(i+2)
        Body[5].append(sim.simxGetObjectHandle(clientID,'LShoulderPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[6].append(sim.simxGetObjectHandle(clientID,'LShoulderRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[7].append(sim.simxGetObjectHandle(clientID,'LElbowYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[8].append(sim.simxGetObjectHandle(clientID,'LElbowRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[9].append(sim.simxGetObjectHandle(clientID,'LWristYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Right Arm
        print '-> Right Arm for NAO : ' + str(i+2)
        Body[10].append(sim.simxGetObjectHandle(clientID,'RShoulderPitch#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[11].append(sim.simxGetObjectHandle(clientID,'RShoulderRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[12].append(sim.simxGetObjectHandle(clientID,'RElbowYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[13].append(sim.simxGetObjectHandle(clientID,'RElbowRoll#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[14].append(sim.simxGetObjectHandle(clientID,'RWristYaw#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        #Left fingers
        print '-> Left Fingers for NAO : ' + str(i+2)
        Body[15].append(sim.simxGetObjectHandle(clientID,'LHand#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger21#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger22#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger23#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger11#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger12#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger13#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger41#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger42#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger43#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger31#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger32#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger33#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb1#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb2#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[16].append(Body[15][i*15:(i+1)*15])
        #Right Fingers
        print '-> Right Fingers for NAO : ' + str(i+2)
        Body[17].append(sim.simxGetObjectHandle(clientID,'RHand#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger41#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger42#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger43#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger31#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger32#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger33#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger21#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger22#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger23#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger11#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger12#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger13#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb1#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb2#'+str(i),sim.simx_opmode_oneshot_wait)[1])
        Body[18].append(Body[17][(i+1)*15:(i+2)*15])
#Allow the joint to move in the sim Simulation
def JointControl(clientID,motionProxy,i,Body):
    print "in Joint Control"
    #Head
    while(sim.simxGetConnectionId(clientID)!=-1):
        #Getting joint's angles from Choregraphe (please check your robot's IP)
        commandAngles = motionProxy.getAngles('Body', False)
        #Allow the robot to move in V-REP using choregraphe's angles
        
        sim.simxSetJointTargetPosition(clientID,Body[0][i],commandAngles[0],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[1][i],commandAngles[1],sim.simx_opmode_oneshot)
        #Bottom
        sim.simxSetJointTargetPosition(clientID,Body[2][i],commandAngles[8],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[3][i],commandAngles[9],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[4][i],commandAngles[10],sim.simx_opmode_oneshot)
        #Wheels
        #sim.simxSetJointTargetPosition(clientID,Body[5][i],commandAngles[11],sim.simx_opmode_oneshot)
        #sim.simxSetJointTargetPosition(clientID,Body[6][i],commandAngles[12],sim.simx_opmode_oneshot)
        #sim.simxSetJointTargetPosition(clientID,Body[7][i],commandAngles[13],sim.simx_opmode_oneshot)
        #Left Arm
        sim.simxSetJointTargetPosition(clientID,Body[5][i],commandAngles[2],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[6][i],commandAngles[3],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[7][i],commandAngles[4],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[8][i],commandAngles[5],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[9][i],commandAngles[6],sim.simx_opmode_oneshot)
        #Right Arm
        sim.simxSetJointTargetPosition(clientID,Body[10][i],commandAngles[11],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[11][i],commandAngles[12],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[12][i],commandAngles[13],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[13][i],commandAngles[14],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[14][i],commandAngles[15],sim.simx_opmode_oneshot)
        #Left Fingers
        sim.simxSetJointTargetPosition(clientID,Body[16][i][0],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][1],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][2],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][3],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][4],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][5],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][6],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][7],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][8],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][9],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][10],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][11],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][12],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][13],commandAngles[7],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[16][i][14],commandAngles[7],sim.simx_opmode_oneshot)
        #Right Fingers
        sim.simxSetJointTargetPosition(clientID,Body[18][i][0],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][1],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][2],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][3],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][4],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][5],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][6],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][7],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][8],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][9],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][10],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][11],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][12],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][13],commandAngles[16],sim.simx_opmode_oneshot)
        sim.simxSetJointTargetPosition(clientID,Body[18][i][14],commandAngles[16],sim.simx_opmode_oneshot)
    print 'End of simulation'

#Get the Handle of only one NAO
def get_first_handles(clientID,Body):    
    print '-> Head for NAO : '+ str(1)
    Body[0].append(sim.simxGetObjectHandle(clientID,'HeadYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[1].append(sim.simxGetObjectHandle(clientID,'HeadPitch#',sim.simx_opmode_oneshot_wait)[1])
    #Bottom
    print '-> Bottom for NAO : ' + str(1)
    Body[2].append(sim.simxGetObjectHandle(clientID,'HipRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[3].append(sim.simxGetObjectHandle(clientID,'HipPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[4].append(sim.simxGetObjectHandle(clientID,'KneePitch#',sim.simx_opmode_oneshot_wait)[1])
    #Wheels
    #print '-> Wheels for NAO : ' + str(1)
    #Body[5].append(sim.simxGetObjectHandle(clientID,'WheelFL#',sim.simx_opmode_oneshot_wait)[1])
    #Body[6].append(sim.simxGetObjectHandle(clientID,'WheelB#',sim.simx_opmode_oneshot_wait)[1])
    #Body[7].append(sim.simxGetObjectHandle(clientID,'WheelFR#',sim.simx_opmode_oneshot_wait)[1])
    #Left Arm
    print '-> Left Arm for NAO : ' + str(1)
    Body[5].append(sim.simxGetObjectHandle(clientID,'LShoulderPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[6].append(sim.simxGetObjectHandle(clientID,'LShoulderRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[7].append(sim.simxGetObjectHandle(clientID,'LElbowYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[8].append(sim.simxGetObjectHandle(clientID,'LElbowRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[9].append(sim.simxGetObjectHandle(clientID,'LWristYaw#',sim.simx_opmode_oneshot_wait)[1])
    #Right Arm
    print '-> Right Arm for NAO : ' + str(1)
    Body[10].append(sim.simxGetObjectHandle(clientID,'RShoulderPitch#',sim.simx_opmode_oneshot_wait)[1])
    Body[11].append(sim.simxGetObjectHandle(clientID,'RShoulderRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[12].append(sim.simxGetObjectHandle(clientID,'RElbowYaw#',sim.simx_opmode_oneshot_wait)[1])
    Body[13].append(sim.simxGetObjectHandle(clientID,'RElbowRoll#',sim.simx_opmode_oneshot_wait)[1])
    Body[14].append(sim.simxGetObjectHandle(clientID,'RWristYaw#',sim.simx_opmode_oneshot_wait)[1])
    #Left fingers
    print '-> Left Fingers for NAO : ' + str(1)
    Body[15].append(sim.simxGetObjectHandle(clientID,'LHand#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger21#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger22#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger23#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger11#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger12#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger13#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger41#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger42#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger43#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger31#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger32#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LFinger33#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb1#',sim.simx_opmode_oneshot_wait)[1])
    Body[15].append(sim.simxGetObjectHandle(clientID,'LThumb2#',sim.simx_opmode_oneshot_wait)[1])
    Body[16].append(Body[15][0:15])
    #Right Fingers
    print '-> Right Fingers for NAO : ' + str(1)
    Body[17].append(sim.simxGetObjectHandle(clientID,'RHand#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger41#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger42#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger43#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger31#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger32#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger33#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger21#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger22#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger23#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger11#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger12#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RFinger13#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb1#',sim.simx_opmode_oneshot_wait)[1])
    Body[17].append(sim.simxGetObjectHandle(clientID,'RThumb2#',sim.simx_opmode_oneshot_wait)[1])
    Body[18].append(Body[17][0:15]) 